 drop table if exists t_schedule_task;
 CREATE TABLE t_schedule_task (
	task_id bigint unsigned NOT NULL AUTO_INCREMENT, 
	task_name varchar(30) COMMENT '调度任务名称', 
	task_mode char(2) COMMENT '调度定时方式 01-cronTask 02-fixedRateTask 03-fixedDelayTask 04-triggerTask', 
	url varchar(60) COMMENT '调度任务URL', 	
	method varchar(10) COMMENT '调用方式 get post', 
	param varchar(200) COMMENT '参数(Json字符串)',
	content_type char(2) COMMENT'01-application/json 02-application/x-www-form-urlencoded',
	cron varchar(20) COMMENT 'cron表达式', 
	initial_delay varchar(20) COMMENT '初始延迟', 
	fixed_delay varchar(20) COMMENT '固定延迟', 
	fixed_rate varchar(20) COMMENT '固定频率', 
	is_imd_exe char(1) COMMENT '是否立即执行 Y-是, N-否', 
	last_execute_begin datetime  COMMENT '上次调度开始时间', 
	last_execute_end datetime  COMMENT '上次调度结束时间', 
	next_execute_time datetime  COMMENT '下次调度开始时间', 
	status char(1) COMMENT '调度状态 0-移除(暂停) 1-正常', 
	proc_state char(2) COMMENT '调度执行状态 00-执行完成(等待执行) 01-执行中',
	create_uid varchar(30) COMMENT '录入人', 
	create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '录入时间', 
	last_modify_uid varchar(30) COMMENT '最后修改人', 
	last_modify_time timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改时间', 
	PRIMARY KEY (task_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='调度任务表';